service: slack-messenger

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  profile: personal
  region: us-east-1

functions:
  alert:
    handler: lib/handler.handler
    events:
      - http:
          path: spam-notification
          method: post
    environment:
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      SLACK_CHANNEL_ID: ${env:SLACK_CHANNEL_ID}
