service: slack-messenger

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  profile: ${env:DEPLOYMENT_AWS_PROFILE}
  region: us-east-1

functions:
  authorize:
    handler: lib/handler.authorize
    environment:
      TOKEN: ${env:TOKEN}
  alert:
    handler: lib/handler.post_notifications
    events:
      - http:
          path: notifications
          method: post
          authorizer: authorize
    environment:
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      SLACK_CHANNEL_ID: ${env:SLACK_CHANNEL_ID}
